version: '2'

services:
#  We will use the external discovery and config service
#  so we won't need these two compose items

#  config:
#    image: hyness/spring-cloud-config-server:1.3.0.RELEASE
#    container_name: config
#    environment:
#      - SPRING_PROFILES_ACTIVE=native
#    ports:
#      - "8888:8888"
#    volumes:
#      - ./config:/config
#    networks:
#      - fineract


#  discovery:
#    image: senacorbitc/discovery
#    container_name: discovery
#    command: java -jar app.jar
#    environment:
#      - eureka.instance.preferIpAdress=true
#    ports:
#      - "8761:8761"
#    networks:
#      - fineract

  cassandra:
    image: cassandra:3.0.1
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      - fineract

  mariadb:
    image: mysql:5.7.18
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
    networks:
        - fineract

  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
      - "61614:61614"
      - "61613:61613"
    networks:
      - fineract

  identity:
    build:
      context: ./fineract-project/identity
    image: bootcamp/identity
    container_name: identity
    hostname: identity.bitc
    working_dir: /
    ports:
      - "8081:8081"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://35.158.23.99:8888
    depends_on:
        - mariadb
        - cassandra
        - activemq
        - discovery
        - config
    networks:
        - fineract

  provisioner:
    build:
      context: ./fineract-project/provisioner
    image: bootcamp/provisioner
    container_name: provisioner
    working_dir: /
#    command: java -jar app.jar
    ports:
      - "9090:9090"
      - "8090:8090"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://35.158.23.99:8888
    depends_on:
        - mariadb
        - cassandra
        - identity
        - activemq
        - config
    networks:
        - fineract

  office:
    build:
      context: ./fineract-project/office
    image: bootcamp/office
    container_name: office
    working_dir: /
    command: java -jar app.jar
    ports:
      - "8082:8082"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://35.158.23.99:8888
    depends_on:
      - mariadb
      - cassandra
      - identity
      - activemq
      - discovery
      - config
    networks:
      - fineract

  customer:
    build:
      context: ./fineract-project/customer
    image: bootcamp/customer
    container_name: customer
    working_dir: /
    command: java -jar app.jar
    ports:
      - "8083:8083"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://35.158.23.99:8888
    depends_on:
      - mariadb
      - cassandra
      - identity
      - activemq
      - discovery
      - config
    networks:
      - fineract

  accounting:
    build:
      context: ./fineract-project/accounting
    image: bootcamp/accounting
    container_name: accounting
    working_dir: /
    command: java -jar app.jar
    ports:
      - "8084:8084"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://35.158.23.99:8888
    depends_on:
      - mariadb
      - cassandra
      - identity
      - activemq
      - discovery
      - config
    networks:
      - fineract

  portfolio:
    build:
      context: ./fineract-project/portfolio
    image: bootcamp/portfolio
    container_name: portfolio
    working_dir: /
    command: java -jar app.jar
    ports:
      - "8085:8085"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://35.158.23.99:8888
    depends_on:
      - mariadb
      - cassandra
      - identity
      - accounting
      - activemq
      - discovery
      - config
    networks:
      - fineract


networks:
  fineract:
